INSERT INTO nationalities (name) VALUES
  ('Afghan'),
  ('Albanian'),
  ('Algerian'),
  ('American'),
  ('Andorran'),
  ('Angolan'),
  ('Antiguan and Barbudan'),
  ('Argentine'),
  ('Armenian'),
  ('Australian'),
  ('Austrian'),
  ('Azerbaijani'),
  ('Bahamian'),
  ('Bahraini'),
  ('Bangladeshi'),
  ('Barbadian'),
  ('Belarusian'),
  ('Belgian'),
  ('Belizean'),
  ('Beninese'),
  ('Bhutanese'),
  ('Bolivian'),
  ('Bosnian and Herzegovinian'),
  ('Botswanan'),
  ('Brazilian'),
  ('British'),
  ('Bruneian'),
  ('Bulgarian'),
  ('Burkinabe'),
  ('Burmese'),
  ('Burundian'),
  ('Cambodian'),
  ('Cameroonian'),
  ('Canadian'),
  ('Cape Verdean'),
  ('Central African'),
  ('Chadian'),
  ('Chilean'),
  ('Chinese'),
  ('Colombian'),
  ('Comorian'),
  ('Congolese (Congo)'),
  ('Congolese (DRC)'),
  ('Costa Rican'),
  ('Croatian'),
  ('Cuban'),
  ('Cypriot'),
  ('Czech'),
  ('Danish'),
  ('Djiboutian'),
  ('Dominican (Dominica)'),
  ('Dominican (Republic)'),
  ('Dutch'),
  ('East Timorese'),
  ('Ecuadorian'),
  ('Egyptian'),
  ('Emirati'),
  ('Equatoguinean'),
  ('Eritrean'),
  ('Estonian'),
  ('Ethiopian'),
  ('Fijian'),
  ('Finnish'),
  ('French'),
  ('Filipino'),
  ('Gabonese'),
  ('Gambian'),
  ('Georgian'),
  ('German'),
  ('Ghanaian'),
  ('Greek'),
  ('Grenadian'),
  ('Guatemalan'),
  ('Guinean'),
  ('Bissau-Guinean'),
  ('Guyanese'),
  ('Haitian'),
  ('Honduran'),
  ('Hungarian'),
  ('I-Kiribati'),
  ('Icelandic'),
  ('Indian'),
  ('Indonesian'),
  ('Iranian'),
  ('Iraqi'),
  ('Irish'),
  ('Israeli'),
  ('Italian'),
  ('Ivorian'),
  ('Jamaican'),
  ('Japanese'),
  ('Jordanian'),
  ('Kazakhstani'),
  ('Kenyan'),
  ('Kittitian/Nevisian'),
  ('Korean'),
  ('Kosovar'),
  ('Kuwaiti'),
  ('Kyrgyzstani'),
  ('Laotian'),
  ('Latvian'),
  ('Lebanese'),
  ('Liberian'),
  ('Libyan'),
  ('Liechtensteiner'),
  ('Lithuanian'),
  ('Luxembourgish'),
  ('Malagasy'),
  ('Malawian'),
  ('Malaysian'),
  ('Maldivian'),
  ('Malian'),
  ('Maltese'),
  ('Marshallese'),
  ('Mauritanian'),
  ('Mauritian'),
  ('Mexican'),
  ('Micronesian'),
  ('Moldovan'),
  ('Monegasque'),
  ('Mongolian'),
  ('Montenegrin'),
  ('Moroccan'),
  ('Mozambican'),
  ('Namibian'),
  ('Nauruan'),
  ('Nepalese'),
  ('New Zealander'),
  ('Nicaraguan'),
  ('Nigerien'),
  ('Nigerian'),
  ('North Macedonian'),
  ('Norwegian'),
  ('Omani'),
  ('Pakistani'),
  ('Palauan'),
  ('Palestinian'),
  ('Panamanian'),
  ('Papua New Guinean'),
  ('Paraguayan'),
  ('Peruvian'),
  ('Polish'),
  ('Portuguese'),
  ('Qatari'),
  ('Romanian'),
  ('Russian'),
  ('Rwandan'),
  ('Saint Lucian'),
  ('Saint Vincentian'),
  ('Samoan'),
  ('San Marinese'),
  ('Sao Tomean'),
  ('Saudi'),
  ('Senegalese'),
  ('Serbian'),
  ('Seychellois'),
  ('Sierra Leonean'),
  ('Singaporean'),
  ('Slovak'),
  ('Slovenian'),
  ('Solomon Islander'),
  ('Somali'),
  ('South African'),
  ('South Sudanese'),
  ('Spanish'),
  ('Sri Lankan'),
  ('Sudanese'),
  ('Surinamese'),
  ('Swazi'),
  ('Swedish'),
  ('Swiss'),
  ('Syrian'),
  ('Taiwanese'),
  ('Tajik'),
  ('Tanzanian'),
  ('Thai'),
  ('Togolese'),
  ('Tongan'),
  ('Trinidadian and Tobagonian'),
  ('Tunisian'),
  ('Turkish'),
  ('Turkmen'),
  ('Tuvaluan'),
  ('Ugandan'),
  ('Ukrainian'),
  ('Uruguayan'),
  ('Uzbek'),
  ('Ni-Vanuatu'),
  ('Vatican'),
  ('Venezuelan'),
  ('Vietnamese'),
  ('Yemeni'),
  ('Zambian'),
  ('Zimbabwean');
