INSERT INTO hobbies (name) VALUES
  ('Reading'),
  ('Traveling'),
  ('Cooking'),
  ('Swimming'),
  ('Hiking'),
  ('Gaming'),
  ('Drawing'),
  ('Dancing'),
  ('Singing'),
  ('Writing'),
  ('Photography'),
  ('Painting'),
  ('Cycling'),
  ('Running'),
  ('Fishing'),
  ('Board Games'),
  ('Chess'),
  ('Puzzles'),
  ('Collecting');
