openapi: '3.0.0'

servers:
  - url: '${SERVER_URL}/api/v1'
    description: API server

paths:
  /jobs/{sessionId}:
    post:
      summary: Create a job
      operationId: createJob

      parameters:
        - in: path
          name: sessionId
          required: true
          schema:
            type: string

      responses:
        '201':
          description: Job created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'

  /stream:
    get:
      summary: Stream text
      operationId: streamText
      responses:
        '200':
          description: A stream of text
          content:
            text/plain:
              schema:
                type: string

  /persons:
    get:
      summary: List persons
      operationId: listPersons

      parameters:
        - $ref: '#/components/parameters/PersonListSearch'
        - $ref: '#/components/parameters/PersonListNationalities'
        - $ref: '#/components/parameters/PersonListHobbies'
        - $ref: '#/components/parameters/PaginationPage'
        - $ref: '#/components/parameters/PaginationLimit'

      responses:
        '200':
          description: A list of persons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'

  /persons/top-nationalities:
    get:
      summary: List top nationalities
      operationId: listTopNationalities
      responses:
        '200':
          description: A list of top nationalities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /persons/top-hobbies:
    get:
      summary: List top hobbies
      operationId: listTopHobbies
      responses:
        '200':
          description: A list of top hobbies
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

components:
  schemas:
    Job:
      type: object
      properties:
        id:
          type: string
          format: uuid
        session_id:
          type: string
        status:
          type: string
          enum: [pending, completed]
        result:
          type: string
      required:
        - id
        - session_id
        - status

    Person:
      type: object
      properties:
        id:
          type: string
          format: uuid
        avatar:
          type: string
          format: uri
        first_name:
          type: string
          maxLength: 100
        last_name:
          type: string
          maxLength: 100
        age:
          type: integer
          minimum: 0
        nationality:
          type: string
          maxLength: 100
        hobbies:
          type: array
          items:
            type: string
            maxLength: 100
          minItems: 0
          maxItems: 10
      required:
        - id
        - avatar
        - first_name
        - last_name
        - age
        - nationality
        - hobbies

  parameters:
    PersonListSearch:
      in: query
      name: search
      schema:
        type: string
        maxLength: 512
      required: false
      description: Search term to filter persons by name

    PersonListNationalities:
      in: query
      name: nationalities
      schema:
        type: array
        items:
          type: string
      required: false
      description: Filter persons by nationality

    PersonListHobbies:
      in: query
      name: hobbies
      schema:
        type: array
        items:
          type: string
      required: false
      description: Filter persons by hobbies

    PaginationPage:
      in: query
      name: page
      schema:
        type: integer
        minimum: 1
        default: 1
      required: false
      description: Page number for pagination

    PaginationLimit:
      in: query
      name: limit
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
      required: false
      description: Number of items per page for pagination
