name: Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Type-check server
        run: npx tsc --noEmit --project server

      - name: Type-check client
        run: npx tsc --noEmit --project client

      - name: Lint code
        run: npm run lint
